'use strict';

module.exports = {
  // 인증
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // 카테고리
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  DEFAULT_CATEGORY_NOT_MODIFIABLE: 'DEFAULT_CATEGORY_NOT_MODIFIABLE',
  DEFAULT_CATEGORY_NOT_DELETABLE: 'DEFAULT_CATEGORY_NOT_DELETABLE',

  // 할일
  TODO_NOT_FOUND: 'TODO_NOT_FOUND',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',

  // 공통
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};
